name: Build Ruby CodeQL pack
description: Builds the Ruby CodeQL pack
runs:
  using: composite
  steps:
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-qltest-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build Extractor
      shell: bash
      run: env "PATH=$PATH:${{ github.workspace }}/codeql" scripts/create-extractor-pack.sh
