name: Comment on PR with framework coverage changes

on:
  workflow_run:
    workflows: ["Check framework coverage changes"]
    types:
      - completed

jobs:
  check:
    name: Check framework coverage differences and comment
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github.event) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Clone self (github/codeql)
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # download artifacts from the PR job:

    - name: Download artifact - MERGE
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUN_ID: ${{ github.event.workflow_run.id }}
      run: |
        gh run download --name "csv-framework-coverage-merge" --dir "out_merge" "$RUN_ID"

    - name: Download artifact - BASE
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUN_ID: ${{ github.event.workflow_run.id }}
      run: |
        gh run download --name "csv-framework-coverage-base" --dir "out_base" "$RUN_ID"

    - name: Download artifact - PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUN_ID: ${{ github.event.workflow_run.id }}
      run: |
        gh run download --name "pr" --dir "pr" "$RUN_ID"

    - name: Check coverage files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUN_ID: ${{ github.event.workflow_run.id }}
      run: |
        PR=$(cat "pr/NR")
        python misc/scripts/library-coverage/compare-files-comment-pr.py \
          out_base out_merge comparison.md "$GITHUB_REPOSITORY" "$PR" "$RUN_ID"
    - name: Upload comparison results
      uses: actions/upload-artifact@v2
      with:
        name: comparison
        path: |
          comparison.md
